In [1]:
import numpy as np
import pandas as pd

In [107]:
prof = pd.read_csv("vk.csv", delimiter=';')

In [108]:
prof.head()

,index,ПОЛ,СТРАНА,ГОРОД,ЛЕТ,ВИЗИТ В ВК,УСТРОЙСТВО ВИЗИТА В ВК,РОДНОЙ ГОРОД,ТЕКУЩАЯ ЗАНЯТОСТЬ,СЕМЕЙНОЕ ПОЛОЖЕНИЕ,...,Библиотека программиста,вакансии для хороших людей,мастер на все руки,МХК,охрана и охранники,педагоги,подслушано у сантехников,работа для медиков в СПБ,сварщики,я - переводчик
0,0,Ж,Россия,Санкт-Петербург,NaN,2020.07.08 16:42,iPhone app,NaN,СПбГУ,NaN,...,0,0,0,0,0,0,0,0,0,0
1,1,М,Россия,Санкт-Петербург,NaN,2020.07.10 00:27,Android app,NaN,Ремонт квартир,NaN,...,0,1,0,0,0,0,0,0,0,0
2,2,М,NaN,NaN,NaN,2020.07.10 01:59,iPhone app,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,3,Ж,Россия,Санкт-Петербург,NaN,2020.07.09 21:52,vk.com,NaN,СПбГУ,NaN,...,0,0,0,0,0,0,0,0,0,0
4,4,Ж,Россия,Санкт-Петербург,NaN,2020.07.10 02:28,m.vk.com,NaN,NaN,NaN,...,0,1,0,0,0,0,0,0,0,0

In [109]:
len(prof[prof["ТЕКУЩАЯ ЗАНЯТОСТЬ"].isnull()]), len(prof)

(104800, 170215)

In [114]:
prof["ГОД НАЧАЛА РАБОТЫ"] = prof["ГОД НАЧАЛА РАБОТЫ"].replace(np.nan, 0)
prof["ГОД ОКОНЧАНИЯ РАБОТЫ"] = prof["ГОД ОКОНЧАНИЯ РАБОТЫ"].replace(np.nan, 0)
prof["ГОД ОКОНЧАНИЯ ВУЗА"] = prof["ГОД ОКОНЧАНИЯ ВУЗА"].replace(np.nan, 0)
prof["ЛЕТ"] = prof["ЛЕТ"].replace(np.nan, 0)
prof["ТЕКУЩАЯ ЗАНЯТОСТЬ"] = prof["ТЕКУЩАЯ ЗАНЯТОСТЬ"].replace(np.nan, "Нет данных")
prof = prof.replace(np.nan, "Нет данных")

In [61]:
from sklearn import preprocessing
#creating labelEncoder
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.

In [115]:
len(prof[prof["ТЕКУЩАЯ ЗАНЯТОСТЬ"]=="Нет работы"]), len(prof)

(104801, 170215)

In [116]:
prof.head()

,index,ПОЛ,СТРАНА,ГОРОД,ЛЕТ,ВИЗИТ В ВК,УСТРОЙСТВО ВИЗИТА В ВК,РОДНОЙ ГОРОД,ТЕКУЩАЯ ЗАНЯТОСТЬ,СЕМЕЙНОЕ ПОЛОЖЕНИЕ,...,Библиотека программиста,вакансии для хороших людей,мастер на все руки,МХК,охрана и охранники,педагоги,подслушано у сантехников,работа для медиков в СПБ,сварщики,я - переводчик
0,0,Ж,Россия,Санкт-Петербург,0.0,2020.07.08 16:42,iPhone app,Нет данных,СПбГУ,Нет данных,...,0,0,0,0,0,0,0,0,0,0
1,1,М,Россия,Санкт-Петербург,0.0,2020.07.10 00:27,Android app,Нет данных,Ремонт квартир,Нет данных,...,0,1,0,0,0,0,0,0,0,0
2,2,М,Нет данных,Нет данных,0.0,2020.07.10 01:59,iPhone app,Нет данных,Нет работы,Нет данных,...,0,0,0,0,0,0,0,0,0,0
3,3,Ж,Россия,Санкт-Петербург,0.0,2020.07.09 21:52,vk.com,Нет данных,СПбГУ,Нет данных,...,0,0,0,0,0,0,0,0,0,0
4,4,Ж,Россия,Санкт-Петербург,0.0,2020.07.10 02:28,m.vk.com,Нет данных,Нет работы,Нет данных,...,0,1,0,0,0,0,0,0,0,0

In [117]:
#готовим фичи
data = prof.apply(preprocessing.LabelEncoder().fit_transform)

In [118]:
data.drop(columns = "ТЕКУЩАЯ ЗАНЯТОСТЬ").head()

,index,ПОЛ,СТРАНА,ГОРОД,ЛЕТ,ВИЗИТ В ВК,УСТРОЙСТВО ВИЗИТА В ВК,РОДНОЙ ГОРОД,СЕМЕЙНОЕ ПОЛОЖЕНИЕ,КОМПАНИЯ,...,Библиотека программиста,вакансии для хороших людей,мастер на все руки,МХК,охрана и охранники,педагоги,подслушано у сантехников,работа для медиков в СПБ,сварщики,я - переводчик
0,0,0,127,2385,0,25873,4,3073,0,11463,...,0,0,0,0,0,0,0,0,0,0
1,1,1,127,2385,0,27759,0,3073,0,15023,...,0,1,0,0,0,0,0,0,0,0
2,2,1,106,1935,0,27851,4,3073,0,11463,...,0,0,0,0,0,0,0,0,0,0
3,3,0,127,2385,0,27604,6,3073,0,11463,...,0,0,0,0,0,0,0,0,0,0
4,4,0,127,2385,0,27880,5,3073,0,11463,...,0,1,0,0,0,0,0,0,0,0

In [119]:
len(set(data["ТЕКУЩАЯ ЗАНЯТОСТЬ"]))

23148

In [128]:
dd = [0 for i in range(len(set(data["ТЕКУЩАЯ ЗАНЯТОСТЬ"])))]
for i in data["ТЕКУЩАЯ ЗАНЯТОСТЬ"]:
    dd[i] += 1
max(dd)

104801

In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
     data.drop(columns = "ТЕКУЩАЯ ЗАНЯТОСТЬ"), data["ТЕКУЩАЯ ЗАНЯТОСТЬ"], test_size=0.2, random_state=42)

In [80]:
from sklearn.neighbors import KNeighborsClassifier


model = KNeighborsClassifier(n_neighbors = 5, metric='minkowski', p=2)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [81]:
len(y_pred) == len(y_test)

True

In [82]:
#рисуем резы
s = 0
for i, x in enumerate(y_test):
    if x != y_pred[i]:
        s+=1
print(str(s/len(y_test) * 100) + "%")

44.011984842698936%

In [ ]:
#если добавлять pipeline
from sklearn.pipeline import Pipeline
model_pipeline = Pipeline(steps=[('preprocessorAll',preprocessorForAllColumns),('classifier', model)])